language: node_js
node_js:
  - 9
  - 8
  - 6
  - 4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - openssl aes-256-cbc -K $encrypted_4ef436d4f4bd_key -iv $encrypted_4ef436d4f4bd_iv
    -in key.json.enc -out key.json -d
  - export CXX=g++-4.8
  - $CXX --version
