version: 2

install_and_test: &install_and_test
  steps:
    - checkout
    - run:
        name: Decrypt JSON key
        command: openssl aes-256-cbc -d -in .circleci/key.json.enc -out .circleci/key.json -k "${KEY}"
    - run:
        name: Install
        command: npm install
    - run:
        name: Test
        command: npm test
        environment:
          GOOGLE_APPLICATION_CREDENTIALS: /root/project/.circleci/key.json
    - run:
        name: Remove key
        command: rm .circleci/key*
        when: always

jobs:
  test_node4:
    docker:
      - image: node:4
    <<: *install_and_test

workflows:
  version: 2
  test:
    jobs:
      - test_node4
