version: 2

install_and_test: &install_and_test
  steps:
    - checkout
    - run:
        name: Decrypt JSON key
        command: openssl aes-256-cbc -d -in .circleci/key.json.enc -out .circleci/key.json -k "${KEY}"
    - run:
        name: Install
        command: npm install
        when: always
    - run:
        name: Test
        command: npm run compile && npm run test-only
        when: always
    - run:
        name: System Tests
        command: npm run system-tests
        environment:
          GOOGLE_APPLICATION_CREDENTIALS: /root/project/.circleci/key.json
    - run:
        name: Remove key
        command: rm .circleci/key.json
        when: always

jobs:
  node4:
    docker:
      - image: node:4
    <<: *install_and_test
  node6:
    docker:
      - image: node:6
    <<: *install_and_test
  node8:
    docker:
      - image: node:8
    <<: *install_and_test
  node10:
    docker:
      - image: node:10
    <<: *install_and_test
  lint:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run check

workflows:
  version: 2
  test:
    jobs:
      - node4
      - node6
      - node8
      - node10
      - lint
